name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
      VITE_COUNTRIES_URL: ${{ secrets.VITE_COUNTRIES_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npx vitest run
